using System.Collections.Generic;

public static class KnownLocations
{
    public static HashSet<string> Locations = new HashSet<string>
    {
        "forest",
        "woods",
        "woodland",
        "thicket",
        "greenwood",
        "forestland",
        "grove",
        "wildwood",
        "wilds",
        "glade",

        "city",
        "suburb",
        "megacity",
        "downtown",
        "megalopolis",
        "central city",
        "urban",
        "new york",
        "london",
        "tel aviv",

        "dungeon",
        "jail",
        "bastille",
        "keep",
        "prison",
        "cage",
        "penitentiary",
        "cell",
        "guardroom",
        "jailhouse",
        "crypt",
        "crypts",
        "dungeons",

        "mountains",
        "peaks",
        "alps",
        "mounts",
        "summit",
        "mountain",
        "mountain ranges",
        "mountaintops",
        "mountaintop",
        "snow",
        "snowy",
        "crags",
        "crag",
        "hill",
        "hills",

        "village",
        "hamlet",
        "vill",
        "bourg",
        "outpost",
        "town",
        "townlet",
        "wild west",
        "cowboy",
        "american frontier",

        "space",
        "universe",
        "galaxy",
        "void",
        "deep space",
        "black hole",
        "spaceship",
        "moon",
        "astronaut",

        "desert",
        "mars",
        "barren",
        "wasteland",
        "wastelands",
        "waste",
        "dune",
        "dunes",
        "heath",
        "no-man's-land",
        "desolation",
        "sands",
        "egypt",
        "shara",

        "sea",
        "ocean",
        "waters",
        "depths",
        "high seas",
        "reef",
        "coral reef",

        "field",
        "plains",
        "fields",
        "plain",
        "meadows",

        "ruins",
        "ruin",
        "temple",
        "graveyard",
        "graveyards",
        "temples",
        "greece",

        "cave",
        "caves",
        "mine",
        "mines",
        "underground",
        "hole",
        "tunnel",
        "cavern",

        "tavern",
        "pub",
        "bar",
        "inn",
        "lodge",
        "saloon",
        "alehouse",

        "office",
        "school",
        "university",
        "collage",
        "campus",
        "saloon",
        "alehouse",

        "japan",
        "asia",
        "china",
        "collage",
        "campus",
        "saloon",
        "alehouse",

        "beach",
        "pirates",
        "ship",
        "boat",

        "sky",
        "cloud",
        "plane",
        "airplane",
        "jet",
        "jet",
        "aircraft",
        "heaven",

        "lava",
        "hell"
    };
}
