using System.Collections.Generic;

public static class KnownLocations
{
    public static Dictionary<string, string> Locations = new Dictionary<string, string>
    {
        {"library", "library"},
        {"archives", "library"},
        {"bookshelf", "library"},
        {"reading room", "library"},
        {"study hall", "library"},
        {"public library", "library"},
        {"reference section", "library"},
        {"digital library", "library"},
        {"manuscript room", "library"},
        {"library stacks", "library"},
        {"bookstore", "library"},
        {"lending library", "library"},
        {"research library", "library"},
        {"reading nook", "library"},

        {"office", "office"},
        {"appartment", "office"},
        {"workplace", "office"},
        {"headquarters", "office"},
        {"cubicle", "office"},
        {"bureau", "office"},
        {"suite", "office"},
        {"workspace", "office"},
        {"study", "office"},
        {"studio", "office"},
        {"co-working space", "office"},
        {"meeting room", "office"},
        {"boardroom", "office"},
        {"conference room", "office"},
        {"admin center", "office"},
        {"executive suite", "office"},
        {"workstation", "office"},
        {"operations center", "office"},
        {"reception", "office"},
        {"front office", "office"},
        {"back office", "office"},
        {"branch office", "office"},

        {"desert", "desert"},
        {"mars", "desert"},
        {"barren", "desert"},
        {"wasteland", "desert"},
        {"wastelands", "desert"},
        {"waste", "desert"},
        {"dune", "desert"},
        {"dunes", "desert"},
        {"heath", "desert"},
        {"no-man's-land", "desert"},
        {"desolation", "desert"},
        {"sands", "desert"},
        {"egypt", "desert"},
        {"shara", "desert"},
        {"sahara", "desert"},
        {"gobi", "desert"},
        {"arid land", "desert"},
        {"sandstorm", "desert"},
        {"oasis", "desert"},
        {"badlands", "desert"},
        {"dustbowl", "desert"},
        {"steppe", "desert"},
        {"drylands", "desert"},
        {"mirage", "desert"},
        {"salt flats", "desert"},
        {"savannah", "desert"},
        {"canyonlands", "desert"},
        {"sand sea", "desert"},
        {"desert plains", "desert"},
        {"sunbaked", "desert"},
        {"parched earth", "desert"},
        {"desertification", "desert"},
        {"rocky desert", "desert"},
        {"desertscape", "desert"},

        {"dungeon", "dungeon"},
        {"jail", "dungeon"},
        {"bastille", "dungeon"},
        {"keep", "dungeon"},
        {"prison", "dungeon"},
        {"cage", "dungeon"},
        {"penitentiary", "dungeon"},
        {"cell", "dungeon"},
        {"guardroom", "dungeon"},
        {"jailhouse", "dungeon"},
        {"dungeons", "dungeon"},
        {"vault", "dungeon"},
        {"chamber", "dungeon"},
        {"citadel", "dungeon"},
        {"gaol", "dungeon"},
        {"holding cell", "dungeon"},
        {"torture chamber", "dungeon"},
        {"barracks", "dungeon"},

        {"beach", "pirates"},
        {"pirates", "pirates"},
        {"ship", "pirates"},
        {"boat", "pirates"},
        {"shore", "pirates"},
        {"port", "pirates"},
        {"sail", "pirates"},
        {"buccaneer", "pirates"},
        {"privateer", "pirates"},
        {"jolly roger", "pirates"},
        {"corsair", "pirates"},
        {"treasure", "pirates"},
        {"parrot", "pirates"},
        {"cannon", "pirates"},
        {"cutlass", "pirates"},
        {"crow’s nest", "pirates"},
        {"galleon", "pirates"},
        {"rum", "pirates"},
        {"swashbuckler", "pirates"},
        {"mutiny", "pirates"},
        {"captain’s cabin", "pirates"},
        {"brig", "pirates"},
        {"pirate code", "pirates"},
        {"sea shanty", "pirates"},
        {"marooned", "pirates"},
        {"plank", "pirates"},
        {"skull and crossbones", "pirates"},
        {"bay", "pirates"},
        {"gulf", "pirates"},
        {"tide", "pirates"},
        {"shoreline", "pirates"},
        {"coast", "pirates"},
        {"archipelago", "pirates"},
        {"cove", "pirates"},
        {"atoll", "pirates"},
        {"waves", "pirates"},
        {"harbor", "pirates"},

        {"village", "village"},
        {"hamlet", "village"},
        {"vill", "village"},
        {"bourg", "village"},
        {"outpost", "village"},
        {"town", "village"},
        {"townlet", "village"},
        {"wild west", "village"},
        {"cowboy", "village"},
        {"american frontier", "village"},
        {"settlement", "village"},
        {"commune", "village"},
        {"small town", "village"},
        {"homestead", "village"},
        {"colony", "village"},
        {"rural area", "village"},
        {"crossroads", "village"},
        {"farmstead", "village"},
        {"shantytown", "village"},
        {"encampment", "village"},
        {"frontier town", "village"},
        {"ranch", "village"},
        {"countryside", "village"},
        {"pastoral community", "village"},
        {"parish", "village"},
        {"fishing village", "village"},
        {"market town", "village"},
        {"plantation", "village"},
        {"manor", "village"},

        {"tavern", "tavern"},
        {"pub", "tavern"},
        {"bar", "tavern"},
        {"inn", "tavern"},
        {"lodge", "tavern"},
        {"saloon", "tavern"},
        {"alehouse", "tavern"},
        {"taproom", "tavern"},
        {"roadhouse", "tavern"},
        {"beer hall", "tavern"},
        {"speakeasy", "tavern"},
        {"cantina", "tavern"},
        {"drinkery", "tavern"},
        {"brewpub", "tavern"},
        {"cocktail lounge", "tavern"},
        {"barroom", "tavern"},
        {"draught house", "tavern"},
        {"public house", "tavern"},
        {"hostel", "tavern"},
        {"drinking den", "tavern"},
        {"gastropub", "tavern"},
        {"watering hole", "tavern"},
        {"wine bar", "tavern"},
        {"canteen", "tavern"},

        {"swamp", "swamp"},
        {"bog", "swamp"},
        {"fen", "swamp"},
        {"marsh", "swamp"},
        {"wetlands", "swamp"},
        {"morass", "swamp"},
        {"quagmire", "swamp"},
        {"bayou", "swamp"},
        {"mire", "swamp"},
        {"flooded", "swamp"},
        {"slough", "swamp"},
        {"mangrove", "swamp"},

        {"japan", "asia"},
        {"asia", "asia"},
        {"china", "asia"},
        {"korea", "asia"},
        {"tibet", "asia"},
        {"taiwan", "asia"},
        {"shinto shrine", "asia"},
        {"torii gate", "asia"},
        {"pagoda", "asia"},
        {"zen garden", "asia"},
        {"feng shui", "asia"},
        {"taoism", "asia"},
        {"buddhism", "asia"},
        {"shaolin temple", "asia"},
        {"samurai", "asia"},
        {"ninja", "asia"},
        {"shogun", "asia"},
        {"geisha", "asia"},
        {"noh theater", "asia"},
        {"confucianism", "asia"},
        {"sumo", "asia"},
        {"tea ceremony", "asia"},
        {"tatami", "asia"},
        {"bonsai", "asia"},
        {"dragon temple", "asia"},
        {"gongen", "asia"},
        {"bamboo forest", "asia"},
        {"rinzai temple", "asia"},

        {"cave", "cave"},
        {"caves", "cave"},
        {"mine", "cave"},
        {"mines", "cave"},
        {"underground", "cave"},
        {"hole", "cave"},
        {"tunnel", "cave"},
        {"cavern", "cave"},
        {"den", "cave"},
        {"pit", "cave"},
        {"sinkhole", "cave"},
        {"lair", "cave"},
        {"crevice", "cave"},
        {"subterranean", "cave"},
        {"passage", "cave"},
        {"shaft", "cave"},
        {"dugout", "cave"},

        {"mountains", "mountain"},
        {"peaks", "mountain"},
        {"alps", "mountain"},
        {"mounts", "mountain"},
        {"summit", "mountain"},
        {"mountain", "mountain"},
        {"mountain ranges", "mountain"},
        {"mountaintops", "mountain"},
        {"mountaintop", "mountain"},
        {"snow", "mountain"},
        {"snowy", "mountain"},
        {"crags", "mountain"},
        {"crag", "mountain"},
        {"hill", "mountain"},
        {"hills", "mountain"},
        {"ridge", "mountain"},
        {"highlands", "mountain"},
        {"cliff", "mountain"},
        {"gorge", "mountain"},
        {"foothill", "mountain"},
        {"pinnacle", "mountain"},
        {"rockface", "mountain"},
        {"slope", "mountain"},
        {"glacier", "mountain"},
        {"pass", "mountain"},
        {"ravine", "mountain"},
        {"upland", "mountain"},

        {"space", "space"},
        {"universe", "space"},
        {"galaxy", "space"},
        {"void", "space"},
        {"deep space", "space"},
        {"black hole", "space"},
        {"spaceship", "space"},
        {"moon", "space"},
        {"astronaut", "space"},
        {"solar system", "space"},
        {"nebula", "space"},
        {"star system", "space"},
        {"cosmos", "space"},
        {"asteroid", "space"},
        {"comet", "space"},
        {"meteor", "space"},
        {"planet", "space"},
        {"space station", "space"},
        {"orbit", "space"},
        {"satellite", "space"},
        {"exoplanet", "space"},
        {"supernova", "space"},
        {"milky way", "space"},
        {"wormhole", "space"},
        {"extraterrestrial", "space"},
        {"space shuttle", "space"},
        {"spacewalk", "space"},
        {"cosmic dust", "space"},
        {"astrobiology", "space"},

        {"forest", "forest"},
        {"woods", "forest"},
        {"woodland", "forest"},
        {"thicket", "forest"},
        {"greenwood", "forest"},
        {"forestland", "forest"},
        {"grove", "forest"},
        {"wildwood", "forest"},
        {"wilds", "forest"},
        {"glade", "forest"},
        {"timberland", "forest"},
        {"wilderness", "forest"},
        {"bushland", "forest"},
        {"hinterland", "forest"},
        {"undergrowth", "forest"},
        {"sylvan", "forest"},
        {"wood", "forest"},

        {"lava", "hell"},
        {"hell", "hell"},
        {"volcano", "hell"},
        {"magma", "hell"},
        {"volcanic", "hell"},
        {"crater", "hell"},
        {"ash cloud", "hell"},
        {"eruption", "hell"},
        {"pyroclastic flow", "hell"},
        {"caldera", "hell"},
        {"geyser", "hell"},
        {"rift zone", "hell"},
        {"lava flow", "hell"},
        {"basalt", "hell"},
        {"scoria", "hell"},
        {"sulfur pits", "hell"},
        {"steam vents", "hell"},
        {"fire pit", "hell"},
        {"smoldering ground", "hell"},
        {"lava tube", "hell"},
        {"molten rock", "hell"},
        {"fumarole", "hell"},
        {"igneous rock", "hell"},
        {"magma chamber", "hell"},
        {"seismic activity", "hell"},

        {"field", "meadow"},
        {"plains", "meadow"},
        {"fields", "meadow"},
        {"plain", "meadow"},
        {"meadows", "meadow"},
        {"meadow", "meadow"},
        {"grassland", "meadow"},
        {"pasture", "meadow"},
        {"moor", "meadow"},
        {"clearing", "meadow"},
        {"valley", "meadow"},
        {"flatlands", "meadow"},
        {"downs", "meadow"},

        {"city", "city"},
        {"suburb", "city"},
        {"megacity", "city"},
        {"downtown", "city"},
        {"megalopolis", "city"},
        {"central city", "city"},
        {"urban", "city"},
        {"new york", "city"},
        {"london", "city"},
        {"tel aviv", "city"},
        {"metropolis", "city"},
        {"borough", "city"},
        {"capital", "city"},
        {"municipality", "city"},
        {"cityscape", "city"},
        {"urban sprawl", "city"},
        {"inner city", "city"},
        {"district", "city"},
        {"precinct", "city"},
        {"neighborhood", "city"},
        {"township", "city"},
        {"cosmopolitan", "city"},
        {"conurbation", "city"},
        {"civic center", "city"},
        {"business district", "city"},
        {"skyline", "city"},
        {"skyscraper", "city"},
        {"plaza", "city"},
        {"hub", "city"},

        {"ruins", "graveyard"},
        {"ruin", "graveyard"},
        {"temple", "graveyard"},
        {"church", "graveyard"},
        {"graveyard", "graveyard"},
        {"graveyards", "graveyard"},
        {"temples", "graveyard"},
        {"holy", "graveyard"},
        {"catacombs", "graveyard"},
        {"cemetery", "graveyard"},
        {"burial ground", "graveyard"},
        {"tomb", "graveyard"},
        {"mausoleum", "graveyard"},
        {"crypt", "graveyard"},
        {"necropolis", "graveyard"},
        {"memorial park", "graveyard"},
        {"burial site", "graveyard"},
        {"resting place", "graveyard"},
        {"tombstone", "graveyard"},
        {"shrine", "graveyard"},
        {"headstone", "graveyard"},
        {"chapel", "graveyard"},
        {"mortuary", "graveyard"},
        {"ossuary", "graveyard"},
        {"funeral grounds", "graveyard"},
        {"sanctum", "graveyard"},
        {"barrow", "graveyard"},
        {"grave", "graveyard"},
        {"sepulcher", "graveyard"},

/*        {"sea", "sea"},
        {"ocean", "sea"},
        {"waters", "sea"},
        {"depths", "sea"},
        {"high seas", "sea"},
        {"reef", "sea"},
        {"coral reef", "sea"},
        {"lagoon", "sea"},
        {"abyss", "sea"},
        {"seabed", "sea"},
        {"atlantis", "sea"},
        {"sunken", "sea"},
        {"sunken city", "sea"},

        "sky",
        "cloud",
        "plane",
        "airplane",
        "jet",
        "jet",
        "aircraft",
        "heaven",*/
    };
}